# Site settings
title: Haney Shoes
email: haneyshoes@gmail.com
url: haneyshoestore.com
description: "A family-owned shoe store in Omaha, NE offering the region's largest selection of safety-toe and soft-toe workboots from Keen, Timberland, Wolverine, and more. Also offers a large selection of walking, casual and athletic shoes and individual fitting for every customer."
skills: "Custom Fitting - Casual and Safety Footwear - Work Apparel - Mobile Shoe Truck"
meta_author: Noto Alex

# Google webmaster tools
google_verify:
  http://haneyshoestore.com/google5bc4ef7ab73c709c.html

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: D92626 #80B3FF
  primary-rgb: "206,36,36" #"128,179,255"
  secondary: FAE9C3 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Haney Shoes
  benson: Benson
  redwing: Red Wing Store
  lincoln: Lincoln

# Postal address (add as many lines as necessary)
benson:
  - line: 6060 Maple St
  - line: Omaha, NE 68104
  - line: 402-556-2022
  - line: Mon - Fri 9AM - 8PM
  - line: Sat 9AM - 5:30PM  Sun Closed

redwing:
  - line: 5018 S 108th St
  - line: Omaha, NE 68137
  - line: 402-339-1542
  - line: Mon Thurs 9AM - 8PM
  - line: Tues Wed Fri 9AM - 6PM
  - line: Sat 9AM - 5PM  Sun Closed

lincoln:
  - line: 6133 Havelock Ave
  - line: Lincoln, NE 68507
  - line: 402-466-7175
  - line: Mon 9AM - 7PM
  - line: Tues - Fri 9AM - 6PM
  - line: Sat 9AM - 5PM  Sun Closed

# Credits content
credits: 'Site created by Alex Noto. Original theme courtesy of Start Bootstrap.'

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
